// <auto-generated />
namespace SDC.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class avatars_key : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(avatars_key));
        
        string IMigrationMetadata.Id
        {
            get { return "201509111628461_avatars_key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
