// <auto-generated />
namespace SDC.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class settings_key : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(settings_key));
        
        string IMigrationMetadata.Id
        {
            get { return "201509111427029_settings_key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
